FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

FROM node:22-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ARG AZURE_OPENAI_ENDPOINT
ARG AZURE_OPENAI_API_KEY
ARG AZURE_OPENAI_DEPLOYMENT
ARG AZURE_OPENAI_API_VERSION
ARG MAX_UPLOAD_MB
ARG MAX_REFERENCE_IMAGES
ARG GENERATION_RATE_LIMIT_PER_MINUTE
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT
ENV AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY
ENV AZURE_OPENAI_DEPLOYMENT=$AZURE_OPENAI_DEPLOYMENT
ENV AZURE_OPENAI_API_VERSION=$AZURE_OPENAI_API_VERSION
ENV MAX_UPLOAD_MB=$MAX_UPLOAD_MB
ENV MAX_REFERENCE_IMAGES=$MAX_REFERENCE_IMAGES
ENV GENERATION_RATE_LIMIT_PER_MINUTE=$GENERATION_RATE_LIMIT_PER_MINUTE

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
